#index:
#    path: /
#    controller: App\Controller\DefaultController::index
app_lucky_number:
  path: /lucky/number
  controller: App\Controller\LuckyController::number

#  App\HomeController:
#    path: /home
#    controller: app/Controller/HomeController
